### PR TITLE
flake8 3.x compatibility

### LINKED ISSUE #12: flake8 3+ support
Hey! Is there any plans to support flake8 3+ ?

Thnx

### PR DESCRIPTION
**Pull request by asottile**
The `entry_point` needs to match the error code which is produced otherwise it is filtered by default:

### before
```console
$ flake8 ../test.py
$
```

### after
```console
$ flake8 ../test.py
../test.py:1:9: M511 - mutable default arg of type Dict
$
```

I was tipped off to this by running with `-vvv`:

```
flake8.style_guide        MainProcess    294 DEBUG    Deciding if "M511" should be reported
flake8.style_guide        MainProcess    294 DEBUG    The user configured "M511" to be "Ignored.Implicitly", "Selected.Implicitly"
flake8.style_guide        MainProcess    294 DEBUG    "M511" will be "Decision.Ignored"
```

Resolves #12

### CODE REVIEW

**Comment by asottile** [comment]
#13 does the same thing as my patch

**Comment by mxr** [comment]
I think #13 is unmaintained - can we reopen this PR and merge it after review? cc @ebeweber @MarcoFalke @freakboy3742

**Review by mxr — COMMENTED** [review]
+1 from me (if it means anything)

**Comment by asottile** [comment]
wouldn't let me reopen, here's a new one: https://github.com/ebeweber/flake8-mutable/pull/20

**Pull request closed without merging**
